import turtle
t = turtle.Turtle()
s = turtle.Screen()
s.title('Logo Interpreter')
t.forward(100)
t.right(90)
t.forward(100)
t.right(90)
t.forward(100)
t.right(90)
t.forward(100)
turtle.done()
